from diamond_board import Diamond
from triangle_board import Triangle

BOARD = Triangle
BOARD_SIZE = 4
EMPTY_CELLS = [6]
EPISODES = 1
LOOKUP_OR_NEURAL = None
NN_DIMENSIONS = [1]
LEARN_RATE_ACTOR = 1
LEARN_RATE_CRITIC = 0
ELIGIBILITY_DECAY_ACTOR = 0
ELIGIBILITY_DECAY_CRITIC = 0
DISCOUNT_FACTOR_ACTOR = None
DISCOUNT_FACTOR_CRITIC = None
INITIAL_EPSILON = 1
EPSILON_DECAY_RATE = 0
EPISODES_BEFORE_VISUALIZATION = 200
FRAME_DELAY = 800
