from triangle_board import Triangle
from diamond_board import Diamond

BOARD = Triangle
BOARD_SIZE = 4
EMPTY_CELLS = [6]
EPISODES = 500
LOOKUP_OR_NEURAL = None
NN_DIMENSIONS = [1]
LEARN_RATE_ACTOR = 0.3
LEARN_RATE_CRITIC = 0.3
ELIGIBILITY_DECAY_ACTOR = 0.5
ELIGIBILITY_DECAY_CRITIC = 0.5
DISCOUNT_FACTOR_ACTOR = 0.9
DISCOUNT_FACTOR_CRITIC = 0.9
INITIAL_EPSILON = 0.9
EPSILON_DECAY_RATE = 0.99
EPISODES_BEFORE_VISUALIZATION = 500
FRAME_DELAY = 50
