from triangle_board import Triangle
from diamond_board import Diamond



BOARD = Triangle

BOARD_SIZE = 4
# EMPTY_CELLS = [3, 4, 5, 6, 7, 9, 10, 11, 13, 14]

BOARD = Diamond
# BOARD_SIZE = 5
EMPTY_CELLS = [7]

EPISODES = 5000
LOOKUP_OR_NEURAL = None
NN_DIMENSIONS = [1]
LEARN_RATE_ACTOR = 0.1
LEARN_RATE_CRITIC = 0.01
ELIGIBILITY_DECAY_ACTOR = 0.9
ELIGIBILITY_DECAY_CRITIC = 0.9
DISCOUNT_FACTOR_ACTOR = 0.99
DISCOUNT_FACTOR_CRITIC = 0.99
INITIAL_EPSILON = 1
EPSILON_DECAY_RATE = 0.998
EPISODES_BEFORE_VISUALIZATION = 5000
FRAME_DELAY = 50
